### ISSUE TITLE
Profile page error

### ISSUE THREAD

**Issue by illethrias** [noplanman/wp-otp#6]
Hi,
after installation of your plugin, on profile .php, there is no possibility to modify any informations only as following: 
![image](https://cloud.githubusercontent.com/assets/24453641/26639532/5a120fda-4625-11e7-9df1-06bb9b9bf575.png) 
When the plugin is deactivated everything is shown normal.

**Comment by noplanman** [comment]
What version of WordPress are you using?
Also, is your screenshot the "complete" options page?

**Comment by illethrias** [comment]
I'm using version 4.1 of WP
yes it is screenshot of complete profile page, there are no Name/Contact/About  sections

**Comment by noplanman** [comment]
Hmm, I can't reproduce this issue, it works fine with a fresh 4.1 on my test environment.
What other plugins do you have installed? Maybe one of them is interfering.

Also, you're really still on version 4.1? I highly recommend you update, WordPress is on 4.8 now.

**Comment by noplanman** [comment]
@illethrias Can you provide any extra info?

**Comment by noplanman** [comment]
@illethrias Still a problem?

**Comment by illethrias** [comment]
Hi, in the mean-time I used something else, I cannot verified it now.
But thanks for your effort

S pozdravom
M. Zbirka

2017-09-11 22:04 GMT+02:00 Armando Lüscher <notifications@github.com>:

**Comment by noplanman** [comment]
Ok, I'll close off here then, as I can't reproduce it. If you do choose to try it again at some point, we can try to dig deeper into this 👍
