### ISSUE TITLE
The right way to change and/or translate message text

### ISSUE THREAD

**Issue by petlund** [noplanman/wp-otp#8]
Should I edit class-wp-otp-public.php or wp-otp.pot.
The only way I succeed in was when I edit class-wp-otp-public.php.

**Comment by noplanman** [comment]
The best way is to contribute a translation for whichever language you need:
https://translate.wordpress.org/projects/wp-plugins/wp-otp

To change texts on the form, check out the available filters!
"Filters" section at https://wordpress.org/plugins/wp-otp/

**Comment by petlund** [comment]
Thanks for a quick response. I will try to contribute with a Swedish translation.

**Comment by noplanman** [comment]
Thanks so much!

From the title, by "change", you meant just translation or also being able to change the text in English?

**Comment by petlund** [comment]
Some texts I want to change because not everyone need to use otp on my site. I will tell a named  group who not need otp that the otp field is unnecessary. I put the changes in class-wp-otp-public.php and use the wp application you gave me a link to for a complete Swedish translation. 

Peter Lundin 
+46 11-495 8438

**Comment by noplanman** [comment]
What exactly do you mean by "named group"?
I've been thinking of moving the OTP input to a separate form, which is often the case when logging into services online. Then only people with OTP active actually get the input field.

**Comment by petlund** [comment]
About named group: I mean the board i our organization.  I want to tell the user. If you don´t in the board you don´t need to use OTP.

Separate login form for otp-user and non-otp-user is maybe a solution. But what happens if you take the wrong form...

**Comment by noplanman** [comment]
I'll be keeping this plugin as simple and minimal as possible.

You may want to check out the [Two-Factor beta plugin](https://wordpress.org/plugins/two-factor/) if you need something more elaborate.
