### ISSUE TITLE
Can it be used to secure a single page?

### ISSUE THREAD

**Issue by engrkabirsaleh** [noplanman/wp-otp#9]
Hello, there!

I would like to start by saying "Thumb up" for your splendid job. And I would like to request that, can this plugin be modify to work on a single page that is, to protect the content of a page?

Looking forward to hearing from you.

Thanks.

**Comment by noplanman** [comment]
Hi @engrkabirsaleh 

Thanks for the kind words! :blush: 

At the moment it cannot be used for single pages, only for the main login to the WordPress Admin panel.
I don't think I'll be implementing it for single pages, as I think that only very very few users would need that.

Have you tried using password protected posts/pages? Maybe that's a better solution for you?
